require('keymaps')
require('plugins.lazy')
require('plugins.misc')
require('plugins.lualine')
require('options')
require('misc')
require('plugins.dap')
require('plugins.gitsigns')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.trouble')
-- require('plugins.ai')
-- require('plugins.cody')
-- require('plugins.copilot')
-- require('plugins.gpt')
-- require('plugins.nvim-llama')
require('plugins.obsidian')
require('plugins.zenmode')

-- vim: ts=8 sts=2 sw=2 et
