prSections:
  - title: My Pull Requests
    filters: is:open
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
notificationsSections:
  - title: All
    filters: ""
  - title: Created
    filters: reason:author
  - title: Participating
    filters: reason:participating
  - title: Mentioned
    filters: reason:mention
  - title: Review Requested
    filters: reason:review-requested
  - title: Assigned
    filters: reason:assign
  - title: Subscribed
    filters: reason:subscribed
  - title: Team Mentioned
    filters: reason:team-mention
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: false
    width: 70
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  notificationsLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}}; lazygit
  prs:
    - key: F
      name: handle pr feedback
      command: >
        wt switch {{.HeadRefName}} -x "opencode --prompt 'use the handle-pr-feedback skill'"
    - key: C
      name: code review
      command: >
        wt switch pr:{{.PrNumber}} -x "opencode --prompt 'use the nextgen-code-review skill to review PR:{{.PrNumber}} against main.'"
theme:
  colors:
    text:
      primary: "#F7F1FF"
      secondary: "#5AD4E6"
      inverted: "#F7F1FF"
      faint: "#3E4057"
      warning: "#FC618D"
      success: "#7BD88F"
    background:
      selected: "#535155"
    border:
      primary: "#948AE3"
      secondary: "#7BD88F"
      faint: "#3E4057"
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: true
pager:
  diff: "diffnav"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
